# Generated by Django 2.0.7 on 2019-06-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Price of product in cents')),
                ('promo_date', models.DateField(help_text='date to apply the new price')),
                ('isActive', models.BooleanField(help_text='date to apply the new price')),
                ('code', models.ForeignKey(help_text='ForeinKey to Product code', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
